# Font
font_family JetBrainsMono Nerd Font
font_size 11.5

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Background (slightly transparent)
background_opacity 0.85

# Padding (makes it feel premium)
window_padding_width 12

# Smooth scrolling
scrollback_lines 10000
enable_audio_bell no
shell /home/zhaolun/.config/kitty/launch-tmux.zsh

# Leave multiplexing to tmux.
map ctrl+shift+enter no_op
map ctrl+shift+t no_op
map ctrl+shift+right no_op
map ctrl+shift+left no_op
map ctrl+shift+] no_op
map ctrl+shift+[ no_op
map ctrl+shift+n no_op
map ctrl+shift+q no_op
map ctrl+shift+w no_op


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
